language: cpp
sudo: required
env:
  matrix:
    - OS_TYPE=centos OS_VERSION=7
    - OS_TYPE=ubuntu OS_VERSION=18.04
compiler:
   - gcc
branches:
  only:
  - master
  - 1.x
#  - stable
before_install:
   - if [[ "$OS_TYPE" == "centos" ]]; then sudo yum -y update           ; fi
   - if [[ "$OS_TYPE" == "ubuntu" ]]; then sudo apt-get update          ; fi
notifications:
  recipients:
    - kbesrv@gmail.com
  email:
    on_success: change
    on_failure: always
script: cd kbe/src && make